@TmsApi_HostAddress = http://localhost:5285

GET {{TmsApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TmsApi_HostAddress}}/api/enrollments/results
Accept: application/json

###

GET {{TmsApi_HostAddress}}/api/enrollments/
Accept: application/json

###

